repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [--style=file]
        entry: clang-format --files=src/** -i
        'types_or': [c++, c, c#, cuda, java, javascript, objective-c, proto]
      - id: cpplint
        entry: cpplint
      # - id: clang-tidy
      # - id: oclint
      # - id: uncrustify
      # - id: cppcheck
      # - id: include-what-you-use
