repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black

# TODO: Add pre-commit hooks for C++ files
# repos:
#   - repo: https://github.com/pocc/pre-commit-hooks
#     rev: v1.3.5
#     hooks:
#       - id: clang-format
#         args: [--style=Google]
#       - id: clang-tidy
#       - id: oclint
#       - id: uncrustify
#       - id: cppcheck
#       - id: cpplint
#       - id: include-what-you-use
